app/purchase/supplier/__init__.py
from app.purchase.supplier import routes

app/purchase/supplier/routes.py
from flask import Blueprint, render_template, redirect, request, url_for
from app.db import connect

bp = Blueprint('supplier', __name__, template_folder='templates')

@bp.route('/purchase/suppliers')
def get_suppliers():
    conn = connect()
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM supplier")
    suppliers = cursor.fetchall()

    cursor.close()
    conn.close()

    return render_template('supplier_list.html', suppliers=suppliers)

@bp.route('/purchase/suppliers/<int:id>')
def get_supplier(id):
    conn = connect()
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM supplier WHERE id = %s", (id,))
    supplier = cursor.fetchone()

    cursor.close()
    conn.close()

    return render_template('supplier_detail.html', supplier=supplier)

@bp.route('/purchase/suppliers/')
def redirect_to_products():
    return redirect(url_for('supplier.get_suppliers'))


@bp.route('/purchase/suppliers/create', methods=['GET', 'POST'])
def create_supplier():
    print("CREATE SUPPLIER")
    if request.method == 'POST':
        print("CREATE SUPPLIER -- POST")
        name = request.form['name']
        contact = request.form['contact']

        conn = connect()
        cursor = conn.cursor()

        cursor.execute("INSERT INTO supplier (name, contact) VALUES (%s, %s)", (name, contact))
        conn.commit()

        cursor.close()
        conn.close()

        return redirect(url_for('supplier.get_suppliers'))

    return render_template('create_supplier.html')

@bp.route('/purchase/suppliers/update/<int:id>', methods=['GET', 'POST'])
def update_supplier(id):
    conn = connect()
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM supplier WHERE id = %s", (id,))
    supplier = cursor.fetchone()

    if request.method == 'POST':
        name = request.form['name']
        contact = request.form['contact']

        cursor.execute("UPDATE supplier SET name = %s, contact = %s WHERE id = %s", (name, contact, id))
        conn.commit()

        cursor.close()
        conn.close()

        return redirect(url_for('supplier.get_suppliers'))

    return render_template('create_supplier.html', supplier=supplier)

@bp.route('/purchase/suppliers/delete/<int:id>', methods=['POST'])
def delete_supplier(id):
    conn = connect()
    cursor = conn.cursor()

    cursor.execute("DELETE FROM supplier WHERE id = %s", (id,))
    conn.commit()

    cursor.close()
    conn.close()

    return redirect(url_for('supplier.get_suppliers'))

app/purchase/supplier/templates/create_supplier.html
{% extends 'base.html' %}

{% block left_column %}
    {% include 'purchase_content.html' %}
{% endblock %}

{% block content %}
    <h4>{% if supplier %}Update Supplier{% else %}Create New Supplier{% endif %}</h4>
    <form method="POST" action="{% if supplier %}{{ url_for('supplier.update_supplier', id=supplier[0]) }}
                                {% else %}{{ url_for('supplier.create_supplier') }}{% endif %}">
        <div class="row mb-3">
            <div class="col-md-6">
                <label for="name" class="form-label">Name:</label>
                <input type="text" class="form-control" id="name" name="name" value="{% if supplier %}{{ supplier[1] }}{% endif %}">
            </div>
            <div class="col-md-6">
                <label for="contact" class="form-label">contact:</label>
                <input type="contact" class="form-control" id="contact" name="contact" value="{% if supplier %}{{ supplier[2] }}{% endif %}">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">{% if supplier %}Update{% else %}Create{% endif %}</button>
            </div>
        </div>
    </form>
{% endblock %}

app/purchase/supplier/templates/supplier_detail.html
{% extends 'base.html' %}

{% block left_column %}
    {% include 'purchase_content.html' %}
{% endblock %}

{% block content %}
    <h4>Supplier {{ supplier[1] }} Details</h4>
    <table class="table table-striped table-bordered">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>contact</th>
        </tr>
        <tr>
            <td>{{ supplier[0] }}</td>
            <td>{{ supplier[1] }}</td>
            <td>{{ supplier[2] }}</td>
        </tr>
    </table>
    {% endblock %}

app/purchase/supplier/templates/supplier_list.html
{% extends 'base.html' %}

{% block left_column %}
    {% include 'purchase_content.html' %}
{% endblock %}

{% block content %}
<h4>Suppliers</h4>
<div class="mt-3 mb-3">
    <a href="{{ url_for('supplier.create_supplier') }}" class="btn btn-primary">New</a>
</div>
<table class="table table-striped table-bordered">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>contact</th>
        <th>Actions</th>
    </tr>
    {% for supplier in suppliers %}
    <tr>
        <td>{{ supplier[0] }}</td>
        <!-- <td><a href="{{ url_for('supplier.get_supplier', id=supplier[0]) }}">{{ supplier[1] }}</a></td> -->
        <td>{{ supplier[1] }}</a></td> <!-- list view is enough, no need for details -->
        <td>{{ supplier[2] }}</td>
        <td>
            <a href="{{ url_for('supplier.update_supplier', id=supplier[0]) }}" class="btn btn-primary">Update</a>
            <form method="POST" action="{{ url_for('supplier.delete_supplier', id=supplier[0]) }}" style="display: inline;">
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}