app/__init__.py
from flask import Flask, Blueprint, render_template

from app.manufacturing import bp as manufacturing_bp
from app.inventory import bp as inventory_bp
from app.purchase import bp as purchase_bp
from app.xtras import bp as xtras_bp

from app.manufacturing.product.routes import bp as product_bp
from app.manufacturing.bom.routes import bp as bom_bp
from app.manufacturing.mo.routes import bp as mo_bp

from app.purchase.po.routes import bp as po_bp
from app.purchase.supplier.routes import bp as supplier_bp

from app.inventory.inventory_item.routes import bp as inventory_item_bp
from app.inventory.stock_move.routes import bp as stock_move_bp

from app.xtras.csv.routes import bp as csv_bp

from app.db import connect

home_bp = Blueprint('app', __name__, template_folder='templates')

@home_bp.route('/', methods=['GET'])
def home():
    return render_template('home.html')

def create_app():
    app = Flask(__name__)
    app.secret_key = 'my_secret_key_here'
    app.register_blueprint(home_bp)
    app.register_blueprint(manufacturing_bp)
    app.register_blueprint(inventory_bp)
    app.register_blueprint(purchase_bp)
    app.register_blueprint(xtras_bp)
    app.register_blueprint(product_bp, db_conn = connect)
    app.register_blueprint(bom_bp, db_conn = connect)
    app.register_blueprint(mo_bp, db_conn = connect)
    app.register_blueprint(po_bp, db_conn = connect)
    app.register_blueprint(supplier_bp, db_conn = connect)
    app.register_blueprint(csv_bp)
    app.register_blueprint(inventory_item_bp, db_conn = connect)
    app.register_blueprint(stock_move_bp, db_conn = connect)

    return app

app = create_app()

app/inventory/__init__.py
from flask import Blueprint, render_template

bp = Blueprint('inventory', __name__, url_prefix='/inventory/', template_folder='templates')

from app.inventory.inventory_item import routes
from app.inventory.stock_move import routes

@bp.route('/', methods=['GET'])
def inventory_home():
    return render_template('inventory.html')

app/manufacturing/__init__.py
from flask import Blueprint, render_template

bp = Blueprint('manufacturing', __name__, url_prefix='/manufacturing/', template_folder='templates')

from app.manufacturing.product import routes
from app.manufacturing.bom import routes
from app.manufacturing.mo import routes
from app.manufacturing import bp

@bp.route('/', methods=['GET'])
def manufacturing_home():
    return render_template('manufacturing.html')

app/purchase/__init__.py
from flask import Blueprint, render_template

bp = Blueprint('purchase', __name__, url_prefix='/purchase/', template_folder='templates')

from app.purchase.po import routes
from app.purchase.supplier import routes


@bp.route('/', methods=['GET'])
def purchase_home():
    return render_template('purchase.html')

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>MiniERP</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                {% block left_column %}{% endblock %}
            </div>
            <div class="col-sm-9">
                <!-- Main column content goes here -->
                <header>
                    <a href="{{ url_for('app.home') }}">
                        <div class="banner-content">
                            <img src="{{ url_for('static', filename='images/rocket100.png') }}" alt="Rocket">
                            <h2>ERP from scratch</h2>
                        </div>
                    </a>
                </header>

                {% block content %}{% endblock %}

                <div class="flash-messages">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="flash-message {{ category }}">{{ message }}</div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                </div>

                <!-- <footer>
                    {% include 'footer.html' %}
                </footer> -->
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const flashMessages = document.querySelectorAll('.flash-message');
            flashMessages.forEach(function(message) {
                message.addEventListener('animationend', function() {
                    message.parentNode.removeChild(message);
                });
            });
        });
    </script>
</body>
</html>

app/templates/footer.html
<footer>
    <p>&copy; 2023 nikalmus</p>
    <p class="description">My playground to experiment with coding an ERP system from scratch</p>
</footer>

app/templates/home.html
{% extends 'base.html' %} 
{% block left_column %}
    {% include 'top_nav.html' %}
{% endblock %}
{% block content %}
    <div class="image-container">
      <img src="{{ url_for('static', filename='images/db-diagram.png') }}" alt="db diagram">
      <div class="patch"></div>
    </div>    
    <h6>How to start:</h6>
    <div class="columns">
        <div class="column">
          <strong>Manufacturing</strong>: create Products and a BOM.<br> 
          Both support CSV import.<br>
          Product duplicates are skipped.<br> 
          CSV for BOM must contain a top product (assembly) and products (component parts) for individual BOM Lines. 
          <a href="{{ url_for('csv.get_csv') }}">Find CSV samples here.</a><br>
          <strong>Purchase</strong>: create Supplier(s).<br>
          Now that you have Suppliers and Products, you can create Purchase Orders either manually or import from CSV.<br>
          Mark PO as completed when items are received.
        </div>
        <div class="column">
          <strong>Inventory:</strong> when PO is marked as completed these records created autmatically:<br>
          <ul>
            <li>Inventory Items for each product on a PO Line,</li>
            <li>Stock Moves from Supplier to Warehouse.</li>
          </ul>
          <strong>Manufacturing</strong>: create an MO (Manufacturing Order).<br>
          Select a BOM for the MO. BOM Lines will populate automatically.<br>
          To mark an MO as Reserved, each BOM Line must have the required quantity of components available as a result of completed POs.<br>
          If the required quantity for each BOM Line is available, reserve the components.<br>
        </div>
        <div class="column">
          <strong>Inventory</strong>: as soon as MO is marked as reserved these actions will be triggered automatically<br>
          <ul>
            <li>Inventory Items for each product on a BOM Line will be updated,</li>
            <li>new Stock Moves from Supplier to Warehouse will be created.</li>
          </ul>
          If MO is cancelled prior to being completed<br>
          <ul>
            <li>new Stock Moves from Factory back to Warehouse will be created,</li>
            <li>Inventory Items will be updated</li>
          </ul>
        </div>
      </div>
           
{% endblock %}

app/templates/top_nav.html
<body>
    <div class="left-column">
    <div class="mt-3 mb-3">
        <a href="{{ url_for('inventory.inventory_home') }}">
            <img src="{{ url_for('static', filename='images/inventory200.png') }}" alt="Inventory" width="140">
            <p>Inventory</p>
        </a>
    </div>
    <div class="mt-3 mb-3">
        <a href="{{ url_for('manufacturing.manufacturing_home') }}">
            <img src="{{ url_for('static', filename='images/manufacturing200.png') }}" alt="Manufacturing" width="140">
            <p>Manufacturing</p>
        </a>
    </div>
    <div class="mt-3 mb-3">
        <a href="{{ url_for('purchase.purchase_home') }}">
            <img src="{{ url_for('static', filename='images/purchase200.png') }}" alt="Purchase" width="140">
            <p>Purchase</p>
    </a>
    </div>
</div>
<footer>
    {% include 'footer.html' %}
</footer>
</body>